
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rémy
 */
public class Competitions extends javax.swing.JFrame {

    /**
     * Creates new form Competitions
     */
    public Competitions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        division1 = new javax.swing.JLabel();
        division2 = new javax.swing.JLabel();
        coupeNationale = new javax.swing.JLabel();
        retour = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 533));
        getContentPane().setLayout(null);

        division1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Division_1.png"))); // NOI18N
        division1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                division1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                division1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                division1MousePressed(evt);
            }
        });
        getContentPane().add(division1);
        division1.setBounds(360, 240, 70, 70);

        division2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Division_2.png"))); // NOI18N
        division2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                division2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                division2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                division2MousePressed(evt);
            }
        });
        getContentPane().add(division2);
        division2.setBounds(620, 240, 70, 70);

        coupeNationale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Coupe_nationale.png"))); // NOI18N
        coupeNationale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coupeNationaleMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                coupeNationaleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coupeNationaleMousePressed(evt);
            }
        });
        getContentPane().add(coupeNationale);
        coupeNationale.setBounds(490, 350, 70, 70);

        retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fleche-retour.png"))); // NOI18N
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retourMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retourMousePressed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(910, 400, 70, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void division1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_division1MouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Division_1_p.png"));
        division1.setIcon(i);
        
        Test t = new Test();
        t.setVisible(true);
    }//GEN-LAST:event_division1MouseClicked

    private void division1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_division1MouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Division_1.png"));
        division1.setIcon(i);
    }//GEN-LAST:event_division1MouseExited

    private void division1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_division1MousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Division_1_p.png"));
        division1.setIcon(i);
    }//GEN-LAST:event_division1MousePressed

    private void division2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_division2MouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Division_2_p.png"));
        division2.setIcon(i);
        
        Test t = new Test();
        t.setVisible(true);
    }//GEN-LAST:event_division2MouseClicked

    private void division2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_division2MouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Division_2.png"));
        division2.setIcon(i);
    }//GEN-LAST:event_division2MouseExited

    private void division2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_division2MousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Division_2_p.png"));
        division2.setIcon(i);
    }//GEN-LAST:event_division2MousePressed

    private void coupeNationaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coupeNationaleMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Coupe_nationale_p.png"));
        coupeNationale.setIcon(i);
        
        Test t = new Test();
        t.setVisible(true);
    }//GEN-LAST:event_coupeNationaleMouseClicked

    private void coupeNationaleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coupeNationaleMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Coupe_nationale.png"));
        coupeNationale.setIcon(i);
    }//GEN-LAST:event_coupeNationaleMouseExited

    private void coupeNationaleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coupeNationaleMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Coupe_nationale_p.png"));
        coupeNationale.setIcon(i);
    }//GEN-LAST:event_coupeNationaleMousePressed

    private void retourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
        
        this.setVisible(false);
    }//GEN-LAST:event_retourMouseClicked

    private void retourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMouseExited

    private void retourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Competitions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Competitions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Competitions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Competitions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Competitions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel coupeNationale;
    private javax.swing.JLabel division1;
    private javax.swing.JLabel division2;
    private javax.swing.JLabel retour;
    // End of variables declaration//GEN-END:variables
}
