/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rémy
 */

import java.awt.BorderLayout;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;


public class InterfaceGraphique extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGraphique
     */
    public InterfaceGraphique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userMode = new javax.swing.JLabel();
        adminMode = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 533));
        getContentPane().setLayout(null);

        userMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        userMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userModeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userModeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userModeMousePressed(evt);
            }
        });
        getContentPane().add(userMode);
        userMode.setBounds(580, 250, 70, 70);

        adminMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/worker.png"))); // NOI18N
        adminMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminModeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminModeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminModeMousePressed(evt);
            }
        });
        getContentPane().add(adminMode);
        adminMode.setBounds(300, 250, 70, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        background.setText("jLabel2");
        getContentPane().add(background);
        background.setBounds(0, 0, 1038, 505);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminModeMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/worker_p.png"));
        adminMode.setIcon(i);
        
        Test t = new Test();
        t.setVisible(true);
    }//GEN-LAST:event_adminModeMouseClicked

    private void adminModeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminModeMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/worker.png"));
        adminMode.setIcon(i);
    }//GEN-LAST:event_adminModeMouseExited

    private void userModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userModeMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/user_p.png"));
        userMode.setIcon(i);
        
        User u = new User();
        u.setVisible(true);
        
    }//GEN-LAST:event_userModeMouseClicked

    private void userModeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userModeMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/user.png"));
        userMode.setIcon(i);
    }//GEN-LAST:event_userModeMouseExited

    private void userModeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userModeMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/user_p.png"));
        userMode.setIcon(i);
    }//GEN-LAST:event_userModeMousePressed

    private void adminModeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminModeMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/worker_p.png"));
        adminMode.setIcon(i);
    }//GEN-LAST:event_adminModeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraphique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminMode;
    private javax.swing.JLabel background;
    private javax.swing.JLabel userMode;
    // End of variables declaration//GEN-END:variables
}
