
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rémy
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allemagne = new javax.swing.JLabel();
        angleterre = new javax.swing.JLabel();
        espagne = new javax.swing.JLabel();
        france = new javax.swing.JLabel();
        italie = new javax.swing.JLabel();
        paysBas = new javax.swing.JLabel();
        portugal = new javax.swing.JLabel();
        russie = new javax.swing.JLabel();
        ligueDesChampions = new javax.swing.JLabel();
        ligueEuropa = new javax.swing.JLabel();
        retour = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 533));
        getContentPane().setLayout(null);

        allemagne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Allemagne.png"))); // NOI18N
        allemagne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allemagneMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allemagneMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                allemagneMousePressed(evt);
            }
        });
        getContentPane().add(allemagne);
        allemagne.setBounds(340, 250, 70, 70);

        angleterre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Angleterre.png"))); // NOI18N
        angleterre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                angleterreMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                angleterreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                angleterreMousePressed(evt);
            }
        });
        getContentPane().add(angleterre);
        angleterre.setBounds(240, 250, 70, 70);

        espagne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Espagne.png"))); // NOI18N
        espagne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espagneMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                espagneMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espagneMousePressed(evt);
            }
        });
        getContentPane().add(espagne);
        espagne.setBounds(140, 250, 70, 70);

        france.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/France.png"))); // NOI18N
        france.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                franceMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                franceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                franceMousePressed(evt);
            }
        });
        getContentPane().add(france);
        france.setBounds(540, 250, 70, 70);

        italie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Italie.png"))); // NOI18N
        italie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                italieMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                italieMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                italieMousePressed(evt);
            }
        });
        getContentPane().add(italie);
        italie.setBounds(440, 250, 70, 70);

        paysBas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pays_bas.png"))); // NOI18N
        paysBas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paysBasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paysBasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paysBasMousePressed(evt);
            }
        });
        getContentPane().add(paysBas);
        paysBas.setBounds(840, 250, 70, 70);

        portugal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Portugal.png"))); // NOI18N
        portugal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                portugalMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                portugalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                portugalMousePressed(evt);
            }
        });
        getContentPane().add(portugal);
        portugal.setBounds(640, 250, 70, 70);

        russie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Russie.png"))); // NOI18N
        russie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                russieMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                russieMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                russieMousePressed(evt);
            }
        });
        getContentPane().add(russie);
        russie.setBounds(740, 250, 70, 70);

        ligueDesChampions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Coupe_LDC.png"))); // NOI18N
        ligueDesChampions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ligueDesChampionsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ligueDesChampionsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ligueDesChampionsMousePressed(evt);
            }
        });
        getContentPane().add(ligueDesChampions);
        ligueDesChampions.setBounds(390, 350, 70, 119);

        ligueEuropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Coupe_EL_p.png"))); // NOI18N
        ligueEuropa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ligueEuropaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ligueEuropaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ligueEuropaMousePressed(evt);
            }
        });
        getContentPane().add(ligueEuropa);
        ligueEuropa.setBounds(590, 350, 70, 119);

        retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fleche-retour.png"))); // NOI18N
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retourMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retourMousePressed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(910, 400, 70, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 502);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void espagneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espagneMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Espagne_p.png"));
        espagne.setIcon(i);
        
        Competitions c = new Competitions();
        c.setVisible(true);
    }//GEN-LAST:event_espagneMouseClicked

    private void espagneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espagneMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Espagne.png"));
        espagne.setIcon(i);
    }//GEN-LAST:event_espagneMouseExited

    private void espagneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espagneMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Espagne_p.png"));
        espagne.setIcon(i);
    }//GEN-LAST:event_espagneMousePressed

    private void angleterreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_angleterreMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Angleterre_p.png"));
        angleterre.setIcon(i);
        
        Competitions c = new Competitions();
        c.setVisible(true);
    }//GEN-LAST:event_angleterreMouseClicked

    private void angleterreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_angleterreMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Angleterre.png"));
        angleterre.setIcon(i);
    }//GEN-LAST:event_angleterreMouseExited

    private void angleterreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_angleterreMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Angleterre_p.png"));
        angleterre.setIcon(i);
    }//GEN-LAST:event_angleterreMousePressed

    private void allemagneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allemagneMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Allemagne_p.png"));
        allemagne.setIcon(i);
        
        Competitions c = new Competitions();
        c.setVisible(true);
    }//GEN-LAST:event_allemagneMouseClicked

    private void allemagneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allemagneMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Allemagne.png"));
        allemagne.setIcon(i);
    }//GEN-LAST:event_allemagneMouseExited

    private void allemagneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allemagneMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Allemagne_p.png"));
        allemagne.setIcon(i);
    }//GEN-LAST:event_allemagneMousePressed

    private void italieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_italieMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Italie_p.png"));
        italie.setIcon(i);
        
        Competitions c = new Competitions();
        c.setVisible(true);
    }//GEN-LAST:event_italieMouseClicked

    private void italieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_italieMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Italie.png"));
        italie.setIcon(i);
    }//GEN-LAST:event_italieMouseExited

    private void italieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_italieMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Italie_p.png"));
        italie.setIcon(i);
    }//GEN-LAST:event_italieMousePressed

    private void franceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_franceMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/France_p.png"));
        france.setIcon(i);
        
        Competitions c = new Competitions();
        c.setVisible(true);
    }//GEN-LAST:event_franceMouseClicked

    private void franceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_franceMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/France.png"));
        france.setIcon(i);
    }//GEN-LAST:event_franceMouseExited

    private void franceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_franceMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/France_p.png"));
        france.setIcon(i);
    }//GEN-LAST:event_franceMousePressed

    private void portugalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_portugalMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Portugal_p.png"));
        portugal.setIcon(i);
        
        Competitions c = new Competitions();
        c.setVisible(true);
    }//GEN-LAST:event_portugalMouseClicked

    private void portugalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_portugalMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Portugal.png"));
        portugal.setIcon(i);
    }//GEN-LAST:event_portugalMouseExited

    private void portugalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_portugalMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Portugal_p.png"));
        portugal.setIcon(i);
    }//GEN-LAST:event_portugalMousePressed

    private void russieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_russieMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Russie_p.png"));
        russie.setIcon(i);
        
        Competitions c = new Competitions();
        c.setVisible(true);
    }//GEN-LAST:event_russieMouseClicked

    private void russieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_russieMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Russie.png"));
        russie.setIcon(i);
    }//GEN-LAST:event_russieMouseExited

    private void russieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_russieMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Russie_p.png"));
        russie.setIcon(i);
    }//GEN-LAST:event_russieMousePressed

    private void paysBasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysBasMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Pays_bas_p.png"));
        paysBas.setIcon(i);
        
        Competitions c = new Competitions();
        c.setVisible(true);
    }//GEN-LAST:event_paysBasMouseClicked

    private void paysBasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysBasMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Pays_bas.png"));
        paysBas.setIcon(i);
    }//GEN-LAST:event_paysBasMouseExited

    private void paysBasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysBasMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Pays_bas_p.png"));
        paysBas.setIcon(i);
    }//GEN-LAST:event_paysBasMousePressed

    private void ligueDesChampionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ligueDesChampionsMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Coupe_LDC_p.png"));
        ligueDesChampions.setIcon(i);
        
        Test t = new Test();
        t.setVisible(true);
    }//GEN-LAST:event_ligueDesChampionsMouseClicked

    private void ligueDesChampionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ligueDesChampionsMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Coupe_LDC.png"));
        ligueDesChampions.setIcon(i);
    }//GEN-LAST:event_ligueDesChampionsMouseExited

    private void ligueDesChampionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ligueDesChampionsMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Coupe_LDC_p.png"));
        ligueDesChampions.setIcon(i);
    }//GEN-LAST:event_ligueDesChampionsMousePressed

    private void ligueEuropaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ligueEuropaMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Coupe_EL_p.png"));
        ligueEuropa.setIcon(i);
        
        Test t = new Test();
        t.setVisible(true);
    }//GEN-LAST:event_ligueEuropaMouseClicked

    private void ligueEuropaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ligueEuropaMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Coupe_EL.png"));
        ligueEuropa.setIcon(i);
    }//GEN-LAST:event_ligueEuropaMouseExited

    private void ligueEuropaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ligueEuropaMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Coupe_EL_p.png"));
        ligueEuropa.setIcon(i);
    }//GEN-LAST:event_ligueEuropaMousePressed

    private void retourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
        
        this.setVisible(false);
    }//GEN-LAST:event_retourMouseClicked

    private void retourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMouseExited

    private void retourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allemagne;
    private javax.swing.JLabel angleterre;
    private javax.swing.JLabel background;
    private javax.swing.JLabel espagne;
    private javax.swing.JLabel france;
    private javax.swing.JLabel italie;
    private javax.swing.JLabel ligueDesChampions;
    private javax.swing.JLabel ligueEuropa;
    private javax.swing.JLabel paysBas;
    private javax.swing.JLabel portugal;
    private javax.swing.JLabel retour;
    private javax.swing.JLabel russie;
    // End of variables declaration//GEN-END:variables
}
